#!/bin/bash
# Wrapper around CHP entrypoint that changes defaults slightly
# to be more appropriate when run in a container.

if [[ "$@" != *"--api-ip"* ]]; then
  # Default api-ip to all interfaces in docker,
  # so that it is accessible to other containers
  # and when port-forwarding is requested.
  ARGS="--api-ip=0.0.0.0"
fi

exec configurable-http-proxy $ARGS $@
